### ISSUE TITLE
Run a straight line spline on Zenith

### ISSUE THREAD

**Issue by ianmcvann** [TheGreenMachine/Neo-Zenith#12]
Use the new Cheesy Poof PathBuilder to run a straight line.

**Comment by richiksc** [comment]
@ianmcvann @Aryan9101 @kooryan Are we still pursuing this issue? I think our foucs has shifted to TrajectoryGenerator on Zeta, especially given the encoder issues on Zenith. We should delete this issue if we're no longer pursuing it.

**Comment by kooryan** [comment]
@richiksc Yes. It is good practice to have splines running on all robots and will help us prepare for any situation that comes up similar to Zenith’s issue.

**Comment by richiksc** [comment]
@kooryan Except any robots we build in the future won't have Zenith's issue.

**Comment by kooryan** [comment]
@richiksc we never know that. As Mr. Deutsch said, it’s still good practice. It’s not a super high priority, but once we get all the high importance items completed, it will be back to troubleshooting splines on Zenith
